common: &common
  adapter: postgresql
  encoding: unicode
  username: jevan
  password: password
  host: localhost

development:
  <<: *common
  database: huali_dev

test:
  <<: *common
  database: huali_test

staging:
  adapter: postgresql
  encoding: unicode
  database: huali_dev
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: huali_production
  pool: 18
  username: huali
  password: IShveVzpaUKhWc4bxNAwoQ=
  host: localhost
