common: &common
  adapter: postgresql
  encoding: unicode
  username: jevan
  password: password
  host: localhost

development:
  <<: *common
  database: huali_wechat_dev

test:
  <<: *common
  database: huali__wechat_test

staging:
  adapter: postgresql
  encoding: unicode
  database: huali_wechat_production
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: huali_wechat_production
  pool: 20
  username: huali
  password: IShveVzpaUKhWc4bxNAwoQ=
  host: localhost
