default: &default
appid: <%= ENV['WECHAT_APPID'] %>
secret: <%= ENV['WECHAT_APP_SECRET'] %>
token: <%= ENV['WECHAT_TOKEN'] %>
access_token: <%= ENV['WECHAT_ACCESS_TOKEN'] %>

production: 
<<: *dfault

staging: 
<<: *default

development: 
<<: *default

test: 
<<: *default
